### ISSUE TITLE
Stage stage shows up in API Gateway

### ISSUE THREAD

**Issue by chadkluck** [chadkluck/serverless-webservice-template-for-pipeline-atlantis#1]
There is an extra stage called Stage that shows up in API Gateway.

Add the following to Globals in the CF template:

```yaml
Globals:

# [.......]

  Api:
    OpenApiVersion: 3.0.0 # Prevents extra stage called Stage in API Gateway https://www.internetkatta.com/how-to-prevent-aws-sam-from-creating-the-default-stage-in-api-gateway-stage
```
