### ISSUE TITLE
S3 Buckets should require requests to use Secure Socket Layer

### ISSUE THREAD

**Issue by chadkluck** [chadkluck/serverless-webservice-template-for-pipeline-atlantis#2]
Add a bucket policy for the App and Cache data storage:

```yaml

# [...........]
# Place after the bucket definition

  # -- S3 Bucket Policy for Lambda App Data Storage --
  AppDataS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AppDataS3Bucket
      PolicyDocument:
        Statement:
              - Sid: "DenyNonSecureTransportAccess"
                Effect: Deny
                Principal: "*"
                Action: "s3:*"
                Resource:
                  - !GetAtt AppDataS3Bucket.Arn
                  - !Join [ '', [ !GetAtt AppDataS3Bucket.Arn, '/*' ] ]
                Condition:
                  Bool:
                    "aws:SecureTransport": false
```
