### ISSUE TITLE
Add npm audit and update Artifact section in buildspec

### ISSUE THREAD

**Issue by chadkluck** [chadkluck/serverless-webservice-template-for-pipeline-atlantis#3]
There is a way to run an npm audit for vulnerabilities and fail the deployment if there are vulnerable packages. This seems like a good thing to add to a template to make the application more secure.

```yaml
  pre_build:
    commands:
      # Install dependencies needed for application
      - cd app
      - npm ci

      # Perform a fix to move us forward, then check to make sure there were no unresolved high fixes
      - npm audit fix --force
      - npm audit --audit-level=high
      
      - cd ..

      # Generate Key in SSM for cache
      - chmod a+x tools/generate-put-keys.sh
      - tools/generate-put-keys.sh $PARAM_STORE_PATH "256" $AWS_REGION $ACCOUNT_ID 
```

Since we are doing an install, we should bring those artifacts over with:

```yaml
artifacts:
  files:
    - '**/*'
    # - template-export.yml
    # - template-configuration.json
```
